requiredParams:
  name: PagingSource by Alish
  description: Create PagingSource

optionalParams:
  category: automotive
  formFactor: automotive
  constraints:
    - kotlin

widgets:
  - stringParameter:
      id: pagingSourcePrefix
      name: PagingSource Prefix
      constraints:
        - nonempty
        - unique
      default: Blank

globals:
  - stringParameter:
      id: pagingSourcePackage
      value: ${pagingSourcePrefix.camelCaseToUnderlines()}

  - stringParameter:
      id: pagingSourceName
      value: ${pagingSourcePrefix}PagingSource

  - stringParameter:
      id: pagingSourceApiService
      value: ${pagingSourcePrefix}ApiService

recipe:
  - instantiateAndOpen:
      from: root/src/PagingSource.kt.ftl
      to: ${srcOut}/${pagingSourceName}.kt