requiredParams:
  name: Use Case by Alish
  description: Create Use Case

optionalParams:
  category: automotive
  formFactor: automotive
  constraints:
    - kotlin

widgets:
  - stringParameter:
      id: useCasePrefix
      name: Use Case Prefix
      constraints:
        - nonempty
        - unique
      default: Blank

globals:
  - stringParameter:
      id: useCaseName
      value: ${useCasePrefix}UseCase

recipe:
  - instantiateAndOpen:
      from: root/src/UseCase.kt.ftl
      to: ${srcOut}/${useCaseName}.kt