requiredParams:
  name: Repository by Alish
  description: Create Repository and RepositoryImpl

optionalParams:
  category: automotive
  formFactor: automotive
  constraints:
    - kotlin

widgets:
  - stringParameter:
      id: repositoryPrefix
      name: Repository Prefix
      constraints:
        - nonempty
        - unique
      default: Blank

globals:
  - stringParameter:
      id: repositoryName
      value: ${repositoryPrefix}Repository

  - stringParameter:
      id: repositoryNameImpl
      value: ${repositoryPrefix}RepositoryImpl

  - stringParameter:
      id: repositoryApiService
      value: ${repositoryPrefix}ApiService

recipe:
  - instantiateAndOpen:
      from: root/src/Repository.kt.ftl
      to: ${srcOut}/${repositoryName}.kt

  - instantiateAndOpen:
      from: root/src/RepositoryImpl.kt.ftl
      to: ${srcOut}/${repositoryNameImpl}.kt